// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu9U2I7ntW3vG8fU2nXwaK-vtQcfO4Ta8',
    appId: '1:327446972565:web:2ce46118081ecd3444339c',
    messagingSenderId: '327446972565',
    projectId: 'jualbuku-37de7',
    authDomain: 'jualbuku-37de7.firebaseapp.com',
    storageBucket: 'jualbuku-37de7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFNDmMhXuJopmFmf4aUfNm7d-0hrQu_H0',
    appId: '1:327446972565:android:198cd9f99da40e6f44339c',
    messagingSenderId: '327446972565',
    projectId: 'jualbuku-37de7',
    storageBucket: 'jualbuku-37de7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWAxeCeaX3_jMbgtCujIc9Thqblx-9QLg',
    appId: '1:327446972565:ios:a875eb92deea51bd44339c',
    messagingSenderId: '327446972565',
    projectId: 'jualbuku-37de7',
    storageBucket: 'jualbuku-37de7.appspot.com',
    iosClientId: '327446972565-apkpma2q6cl35i123q3of56gn960tk4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.uts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWAxeCeaX3_jMbgtCujIc9Thqblx-9QLg',
    appId: '1:327446972565:ios:a875eb92deea51bd44339c',
    messagingSenderId: '327446972565',
    projectId: 'jualbuku-37de7',
    storageBucket: 'jualbuku-37de7.appspot.com',
    iosClientId: '327446972565-apkpma2q6cl35i123q3of56gn960tk4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.uts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu9U2I7ntW3vG8fU2nXwaK-vtQcfO4Ta8',
    appId: '1:327446972565:web:b8ae8a681c22bd3644339c',
    messagingSenderId: '327446972565',
    projectId: 'jualbuku-37de7',
    authDomain: 'jualbuku-37de7.firebaseapp.com',
    storageBucket: 'jualbuku-37de7.appspot.com',
  );

}